export const templates = {
  pauta:
    '# Pauta de reunião NEXUS\n\nData e duração prevista:\nObjetivo em uma frase:\nParticipantes e funções:\n\n## Evidências novas\nFonte pública, data e contexto:\n\n## Pendências\nTarefa | Responsável | Prazo | Status\n\n## Decisões necessárias\nQuestão | Alternativas | Critérios | Conflitos de interesse\n\n## Decisões registradas\nDecisão | Justificativa | Responsável | Data de revisão\n\n## Próximas ações\nAção | Responsável | Prazo | Como verificar\n\nEvitar identificação de terceiros e dados privados na versão pública.\n',
  raci: '# Matriz RACI NEXUS\n\nProjeto:\nVersão e data:\n\nR = responsável por executar; A = aprovador final; C = consultado; I = informado. Definir um A por atividade.\n\nAtividade | R | A | C | I\nDiagnóstico | | | |\nDesenho do piloto | | | |\nRevisão de riscos | | | |\nExecução | | | |\nMonitoramento | | | |\nComunicação | | | |\nPrestação de contas | | | |\n\nAtribuições dependem de aceite das pessoas e autorização institucional.\n',
  scorecard:
    '# Scorecard de desenvolvimento NEXUS\n\nDocumento privado. Preencher somente com consentimento e finalidade definida.\nPessoa:\nPeríodo:\nConversa de feedback:\n\nDimensão | Evidência observável | Contexto e apoios | Próxima ação | Revisão\nCoragem | | | |\nHumildade | | | |\nResiliência | | | |\nDisciplina | | | |\nLealdade | | | |\nIntegridade | | | |\nPensamento crítico | | | |\nTrabalho em equipe | | | |\nServiço | | | |\n\nA nota 1–5, se usada, deve ser acompanhada de exemplo e contexto. Não atribuir valor pessoal, diagnóstico ou decisão automática. Garantir oportunidade de resposta e considerar acessibilidade.\n',
  adesao:
    '# Termo institucional de adesão NEXUS\n\nMinuta para leitura e validação institucional. Não representa assinatura ou adesão concluída.\n\nDeclaro que conheci os princípios do NEXUS Brasil e desejo contribuir voluntariamente, respeitando legalidade, dignidade humana, pluralismo, proteção de dados, ciência e prestação de contas. Comprometo-me a discordar com respeito, declarar conflitos e comunicar limites de participação.\n\nReconheço que a lealdade a princípios não significa obediência pessoal. As funções serão construídas com meu interesse e aceite, dentro de permissões documentadas. Resultados de autorrelato não substituem avaliação humana.\n\nNome:\nVersão da ementa lida:\nÁrea de interesse:\nCondições de participação e acessibilidade:\nResponsável pela integração:\nData:\nAssinatura por mecanismo definido pela instituição:\n\nNão publicar este documento preenchido no repositório ou no site.\n',
  conduta:
    '# Código de Conduta NEXUS Brasil\n\nVersão pública 1.0 · 08/09/2026 · Base: ementa institucional de 07/09/2026.\n\n1. Respeitar a dignidade humana, o pluralismo e as instituições democráticas.\n2. Separar fatos, hipóteses e opiniões.\n3. Discordar de ideias com respeito às pessoas.\n4. Cumprir compromissos viáveis ou comunicar dificuldades.\n5. Preservar informações privadas e acesso por finalidade.\n6. Declarar conflitos de interesse.\n7. Receber feedback e corrigir erros.\n8. Usar o nome do NEXUS apenas dentro de responsabilidades autorizadas.\n9. Manter compromisso com princípios, integridade e transparência.\n10. Registrar decisões e prestar contas.\n\nSituações de conduta requerem escuta, documentação, proporcionalidade, direito de resposta e revisão humana. O desenvolvimento pode incluir orientação, plano de melhoria e revisão de responsabilidades.\n',
  metodologia:
    '# Metodologia da autoavaliação NEXUS\n\nVersão 1.1.0 · 08/09/2026. Instrumento exploratório, sem estudo de validação psicométrica apresentado.\n\n## Estrutura\n30 afirmações da versão anterior, distribuídas em 6 dimensões com 5 itens cada. Escala de 1 a 5; itens inversos usam 6 menos a resposta. Dimensões variam de 5 a 25 e total de 30 a 150. A ordem é embaralhada; a interface mostra seis blocos neutros de cinco itens.\n\n## Consistência exploratória\nValor inicial 100. Subtrair 12 por diferença superior a 2 entre cada um dos 11 pares predefinidos; subtrair 6 por resposta na direção máxima que ultrapasse 24. Duração abaixo de 180 segundos subtrai 15; abaixo de 90 segundos subtrai outros 25. Limitar o resultado entre 0 e 100.\nAlta: 80 ou mais. Moderada: 60 a 79. Baixa: abaixo de 60.\n\n## Encaminhamento\nBaixa: tentativa não utilizável para ingresso segundo a regra institucional; requer conversa e revisão de contexto. Total de pelo menos 135, menor dimensão de pelo menos 19 e consistência alta: forte alinhamento declarado, sujeito a validação. Total de pelo menos 120, todas as dimensões de pelo menos 17 e consistência alta ou moderada: pode avançar à conversa, com atenção adicional quando moderada. Outros resultados recebem orientação de desenvolvimento. Nenhuma pontuação gera ingresso automático.\n\n## Limitações\nA consistência é heurística. Pares relacionados não são necessariamente equivalentes. Respostas idealizadas não demonstram mentira. Duração não é medida de caráter; acessibilidade, interrupções e contexto alteram o preenchimento. Não há norma populacional, sensibilidade, especificidade, validade de construto ou confiabilidade demonstradas. Necessidades de organização não são falha moral. Decisões exigem exemplos, convivência, escuta e possibilidade de contestação.\n\n## Registro\nSomente resultado final e indicadores agregados ficam no navegador, com nome, e-mail, código e datas, mediante consentimento. Respostas individuais não são armazenadas. Nenhum envio automático ocorre. Código aleatório identifica o relatório, mas não é assinatura digital.\n\n## Carência\nTrês meses de calendário, preservando horário; quando o dia não existe no mês de destino, usar o último dia daquele mês. Datas exibidas em America/Fortaleza. Vale para todos os resultados, inclusive avaliações anteriores. Armazenamento e bloqueio são locais; verificação do histórico entre dispositivos depende da coordenação.\n\n## Revisões futuras\nQuestões situacionais, escolhas entre alternativas plausíveis e estudos com especialistas podem ser avaliados em versões futuras. Revisão por IA não equivale a validação científica ou auditoria independente. Não alterar a pontuação silenciosamente: manter versão, documentação e histórico.\n',
};
